var MODE=new HAPIEnum();var STATE=new HAPIEnum();var DIRECTION=new HAPIEnum();var FUNCTION=new HAPIEnum();var BOUNDS=new HAPIEnum();DIRECTION.add(['UP','DOWN','LEFT','RIGHT']);BOUNDS.add(['XL','XR','YT','YB']);var CONTROLS={keycodes:{up:38,down:40,left:37,right:39,btnA:90,btnB:88,btnC:67,start:13},up:{count:0,pressed:false,held:false},down:{count:0,pressed:false,held:false},left:{count:0,pressed:false,held:false},right:{count:0,pressed:false,held:false},btnA:{count:0,pressed:false,held:false},btnB:{count:0,pressed:false,held:false},btnC:{count:0,pressed:false,held:false},start:{count:0,pressed:false,held:false},};var MOUSE={x:640,y:360};var GLOBAL_VARS={};document.onkeydown=function(e){for(var i in CONTROLS.keycodes)
if(e.keyCode==CONTROLS.keycodes[i])
CONTROLS[i]={count:CONTROLS[i].count+1,held:true,pressed:CONTROLS[i].count==0};};document.onkeyup=function(e){for(var i in CONTROLS.keycodes)
if(e.keyCode==CONTROLS.keycodes[i])
CONTROLS[i]={count:0,pressed:false,held:false};};window.requestAnimFrame=(function(callback){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60);};})();var frameNow,frameThen=performance.now(),frameDelta,frameInterval=1000/60,frameAccumulator=0;var moveNow,moveThen=performance.now(),moveDelta,moveInterval=1000/60,moveAccumulator=0,moveLoop=0;var TO_RADIANS=Math.PI/180.0;var calcSpeed=function(s,md,mi){return moveLoop>1?0:s*(typeof(md)=="undefined"?moveDelta:md)*(typeof(mi)=="undefined"?moveInterval:mi);};var calcSpeedPixel=function(s,md,mi){return calcSpeed(s/300,md,mi);};var hitTest=function(sprite1,sprite2){if((sprite1.position.x-((typeof sprite1.colWidth=="undefined"?sprite1.width:sprite1.colWidth)*sprite1.anchor.x))+(typeof sprite1.colWidth=="undefined"?sprite1.width:sprite1.colWidth)>(sprite2.position.x-((typeof sprite2.colWidth=="undefined"?sprite2.width:sprite2.colWidth)*sprite2.anchor.x)))
if((sprite1.position.x-((typeof sprite1.colWidth=="undefined"?sprite1.width:sprite1.colWidth)*sprite1.anchor.x))<(sprite2.position.x-((typeof sprite2.colWidth=="undefined"?sprite2.width:sprite2.colWidth)*sprite2.anchor.x))+(typeof sprite2.colWidth=="undefined"?sprite2.width:sprite2.colWidth))
if((sprite1.position.y-((typeof sprite1.colHeight=="undefined"?sprite1.height:sprite1.colHeight)*sprite1.anchor.y))+(typeof sprite1.colHeight=="undefined"?sprite1.height:sprite1.colHeight)>(sprite2.position.y-((typeof sprite2.colHeight=="undefined"?sprite2.height:sprite2.colHeight)*sprite2.anchor.y)))
if((sprite1.position.y-((typeof sprite1.colHeight=="undefined"?sprite1.height:sprite1.colHeight)*sprite1.anchor.y))<(sprite2.position.y-((typeof sprite2.colHeight=="undefined"?sprite2.height:sprite2.colHeight)*sprite2.anchor.y))+(typeof sprite2.colHeight=="undefined"?sprite2.height:sprite2.colHeight))
return true;return false;};var stage=new PIXI.Container();var renderer=new PIXI.autoDetectRenderer(1280,720,{antialias:true,transparent:true,resolution:1});var objects=[];var resizeFrame=function(){document.getElementsByTagName('canvas')[0].style.height=(window.document.documentElement.clientHeight<(window.document.documentElement.clientWidth/1280)*720?(window.document.documentElement.clientHeight<720?window.document.documentElement.clientHeight:720):(window.document.documentElement.clientWidth<1280?(window.document.documentElement.clientWidth/1280)*720:720))+'px';document.getElementsByTagName('canvas')[0].style.width=(window.document.documentElement.clientHeight<(window.document.documentElement.clientWidth/1280)*720?(window.document.documentElement.clientHeight<720?(window.document.documentElement.clientHeight/720)*1280:1280):(window.document.documentElement.clientWidth<1280?window.document.documentElement.clientWidth:1280))+'px';document.getElementsByTagName('canvas')[0].style.top=(window.document.documentElement.clientHeight<(window.document.documentElement.clientWidth<1280?(window.document.documentElement.clientWidth/1280)*720:720)?0:(window.document.documentElement.clientHeight-(window.document.documentElement.clientWidth<1280?(window.document.documentElement.clientWidth/1280)*720:720))/2)+'px';}
window.addEventListener('resize',function(){resizeFrame();});var gameInit=function(){};var gameExit=function(){_gameLoopRunning=false;};var _gameLogic=function(){gameLogicPRE();_runObjectLogic();_organiseStage(stage);gameLogicPOST();};var _gameRender=function(){gameRenderPRE();renderer.render(stage);gameRenderPOST();},gameRenderPRE=gameRenderPOST=function(){};var _gameLoopRunning=true,_gameLoop=function(){if(_gameLoopRunning==false)return;requestAnimationFrame(_gameLoop);moveNow=performance.now();moveDelta=moveNow-moveThen;moveThen=moveNow;moveAccumulator+=moveDelta;moveLoop=0;while(moveAccumulator>=moveInterval){moveAccumulator-=moveInterval;}
_gameLogic();frameNow=performance.now();frameDelta=frameNow-frameThen;frameThen=frameNow;frameAccumulator+=frameDelta;if(frameAccumulator>=frameInterval){while(frameAccumulator>=frameInterval)frameAccumulator-=frameInterval;_gameRender();}};var _runObjectLogic=function(){for(var i=0;i<objects.length;i++)if(typeof objects[i].logic=="function")objects[i].logic();};var _runObjectDestructors=function(reset){for(var i=0;i<objects.length;i++)if(typeof objects[i].destructor=="function")objects[i].destructor();if(typeof reset!="undefined"){var newObjects=[];for(var i=0;i<objects.length;i++)if(typeof objects[i]._permenant=="boolean"&&objects[i]._permenant==true)newObjects.push(objects[i]);objects=newObjects;}};var _organiseStage=function(_stage){for(var i=0;i<_stage.children.length;i++){if(typeof _stage.children[i].children!="undefined"&&_stage.children[i].children.length>0)_organiseStage(_stage.children[i]);if(typeof _stage.children[i]._order=="undefined")_stage.children[i]._order=999999;}
_stage.children.sort(function(a,b){return a._order>b._order?-1:(a._order<b._order?1:0);});};document.addEventListener("DOMContentLoaded",function(){document.body.appendChild(renderer.view);document.getElementsByTagName("canvas")[0].onmousemove=function(e){MOUSE={x:e.offsetX,y:e.offsetY};};resizeFrame();requestAnimFrame(_gameLoop);});var musicLibrary,soundLibrary;var loader=new HAPILoader();var gameLogicPRE=function(){if(gameSceneChange!=gameSceneCurrent){if(typeof gameScenes[gameSceneChange].fade=="function"){if(gameSceneFading==STATE.gameSceneFading.NULL){gameScenes[gameSceneChange].fade();gameSceneFading=STATE.gameSceneFading.ACTIVE;}else if(gameSceneFading==STATE.gameSceneFading.FINISHED){gameSceneFading=STATE.gameSceneFading.NULL;_runObjectDestructors(true);if(typeof gameScenes[gameSceneCurrent].exit=="function")gameScenes[gameSceneCurrent].exit();gameSceneCurrent=gameSceneChange;if(typeof gameScenes[gameSceneCurrent].init=="function")gameScenes[gameSceneCurrent].init();}}else{_runObjectDestructors(true);if(typeof gameScenes[gameSceneCurrent].exit=="function")gameScenes[gameSceneCurrent].exit();gameSceneCurrent=gameSceneChange;if(typeof gameScenes[gameSceneCurrent].init=="function")gameScenes[gameSceneCurrent].init();}}
if(gameSceneFading==STATE.gameSceneFading.NULL&&typeof gameScenes[gameSceneCurrent].logic=="function")gameScenes[gameSceneCurrent].logic();};var gameLogicPOST=function(){for(var i in CONTROLS)if(CONTROLS[i].pressed==true)CONTROLS[i].pressed=false;};STATE.add('gameSceneFading',['NULL','ACTIVE','FINISHED']);var gameScenes={},gameSceneCurrent="null",gameSceneChange="null",gameSceneFading=STATE.gameSceneFading.NULL;gameScenes.null={init:function(){},logic:function(){}};var bg=new PIXI.Graphics();bg.beginFill(0x000000,0.5);bg.drawRect(0,0,renderer.width,renderer.height);bg._order=9999999;bg._permenant=true;stage.addChild(bg);objects.push(bg);var fg=new PIXI.Graphics();fg.beginFill(0x000000,0);fg.drawRect(0,0,renderer.width,renderer.height);fg._order=-9999999;fg._permenant=true;stage.addChild(fg);objects.push(fg);gameScenes.reset={fade:function(){fg.set("0x000000",1,250);setTimeout(function(){gameSceneFading=STATE.gameSceneFading.FINISHED;},275);},init:function(){gameSceneChange=gameSceneChangeReset;}};var setCookie=function(name,val){if(typeof name=="undefined")return;document.cookie=name+"="+(typeof val=="undefined"?"; expires=Thu, 01 Jan 1970 00:00:00 UTC":val+"; expires=Thu, 18 Dec 2020 12:00:00 UTC; path=/");};var getCookie=function(name){var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(name+"=")==0)return c.substring(name.length+1,c.length);}
return null;};var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(input){var output="";var chr1,chr2,chr3,enc1,enc2,enc3,enc4;var i=0;input=Base64._utf8_encode(input);while(i<input.length){chr1=input.charCodeAt(i++);chr2=input.charCodeAt(i++);chr3=input.charCodeAt(i++);enc1=chr1>>2;enc2=((chr1&3)<<4)|(chr2>>4);enc3=((chr2&15)<<2)|(chr3>>6);enc4=chr3&63;if(isNaN(chr2)){enc3=enc4=64;}else if(isNaN(chr3)){enc4=64;}
output=output+
Base64._keyStr.charAt(enc1)+Base64._keyStr.charAt(enc2)+
Base64._keyStr.charAt(enc3)+Base64._keyStr.charAt(enc4);}
return output;},decode:function(input){var output="";var chr1,chr2,chr3;var enc1,enc2,enc3,enc4;var i=0;input=input.replace(/[^A-Za-z0-9\+\/\=]/g,"");while(i<input.length){enc1=Base64._keyStr.indexOf(input.charAt(i++));enc2=Base64._keyStr.indexOf(input.charAt(i++));enc3=Base64._keyStr.indexOf(input.charAt(i++));enc4=Base64._keyStr.indexOf(input.charAt(i++));chr1=(enc1<<2)|(enc2>>4);chr2=((enc2&15)<<4)|(enc3>>2);chr3=((enc3&3)<<6)|enc4;output=output+String.fromCharCode(chr1);if(enc3!=64){output=output+String.fromCharCode(chr2);}
if(enc4!=64){output=output+String.fromCharCode(chr3);}}
output=Base64._utf8_decode(output);return output;},_utf8_encode:function(string){string=string.replace(/\r\n/g,"\n");var utftext="";for(var n=0;n<string.length;n++){var c=string.charCodeAt(n);if(c<128){utftext+=String.fromCharCode(c);}
else if((c>127)&&(c<2048)){utftext+=String.fromCharCode((c>>6)|192);utftext+=String.fromCharCode((c&63)|128);}
else{utftext+=String.fromCharCode((c>>12)|224);utftext+=String.fromCharCode(((c>>6)&63)|128);utftext+=String.fromCharCode((c&63)|128);}}
return utftext;},_utf8_decode:function(utftext){var string="";var i=0;var c=c1=c2=0;while(i<utftext.length){c=utftext.charCodeAt(i);if(c<128){string+=String.fromCharCode(c);i++;}
else if((c>191)&&(c<224)){c2=utftext.charCodeAt(i+1);string+=String.fromCharCode(((c&31)<<6)|(c2&63));i+=2;}
else{c2=utftext.charCodeAt(i+1);c3=utftext.charCodeAt(i+2);string+=String.fromCharCode(((c&15)<<12)|((c2&63)<<6)|(c3&63));i+=3;}}
return string;}};var saveDataDefault={intro:false,exploreArk:false,snailMaze:false,flappyBig:false,knuxShadow:false,sonicEggman:false,mysticRuins:false,fishing:false,ending:false},saveData,saveDataWhich='',saveDataNext='';var getSaveDataFromCookie=function(){try{saveData=getCookie("savedata");saveData=Base64.decode(saveData);saveData=JSON.parse(saveData);}catch(e){saveData={};for(var i in saveDataDefault)saveData[i]=false;}
if(saveData==null){saveData={};for(var i in saveDataDefault)saveData[i]=false;}};var setSaveDataToCookie=function(){var saveDataCookie=JSON.stringify(saveData);saveDataCookie=Base64.encode(saveDataCookie);setCookie("savedata",saveDataCookie);};var saveDataToVar=function(which){if(typeof saveData[which]!="undefined")saveData[which]=true;setSaveDataToCookie();};getSaveDataFromCookie();